name: CI/CD Pipeline with Dynamic Kustomize

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: "Create Dockerfile"
        required: true
        type: boolean
      application:
        description: "Select application type"
        required: true
        type: choice
        options:
          - go-api
          - java-api
          - python-api
          - frontend
          - backend
      aws_region:
        description: "Select AWS Region"
        required: true
        type: choice
        options:
          - us-east-1
          - us-west-2
      env_name:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
      modifications:
        description: "Enter runtime modifications as JSON (Only for go-api & java-api)"
        required: false
        default: "{}"
      atlas_repository:
        description: "Enter your Atlas repository where manifests should be pushed"
        required: true

jobs:
  extract-metadata:
    name: Extract Application Metadata
    runs-on: ubuntu-latest
    outputs:
      namespace: ${{ steps.extract_metadata.outputs.namespace }}
      app_name: ${{ steps.extract_metadata.outputs.app_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Application Name and Namespace from Atlas Repository
        id: extract_metadata
        run: |
          REPO_NAME=$(basename "${{ github.event.inputs.atlas_repository }}" .git)
          APP_NAME=$(echo "$REPO_NAME" | sed 's/-atlas$//')
          NAMESPACE="$APP_NAME"

          echo "app_name=$APP_NAME" >> "$GITHUB_OUTPUT"
          echo "namespace=$NAMESPACE" >> "$GITHUB_OUTPUT"

          echo "✅ Extracted app name: $APP_NAME"
          echo "✅ Extracted namespace: $NAMESPACE"

  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest
    needs: extract-metadata
    env:
      APP_NAME: ${{ needs.extract-metadata.outputs.app_name }}
      NAMESPACE: ${{ needs.extract-metadata.outputs.namespace }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Extracted Variables
        run: |
          echo "✅ APP_NAME=${{ env.APP_NAME }}"
          echo "✅ NAMESPACE=${{ env.NAMESPACE }}"
          echo "✅ APPLICATION=${{ github.event.inputs.application }}"

      - name: Set up Python
        if: ${{ github.event.inputs.dockerfile == 'true' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Fetch generate_dockerfile.py from Gist
        if: ${{ github.event.inputs.dockerfile == 'true' }}
        run: |
          curl -o generate_dockerfile.py https://gist.githubusercontent.com/bgcodehub/9057942959e961954cc71eb22e084d7d/raw/d4fb707c46d2be690818f177bdf324a15996809d/generate_dockerfile.py
          chmod +x generate_dockerfile.py
          ls -l generate_dockerfile.py  # Debug to confirm it’s downloaded

      - name: Generate Dockerfile
        if: ${{ github.event.inputs.dockerfile == 'true' }}
        env:
          APPLICATION: ${{ github.event.inputs.application }}
          PORT: "8080"
        run: |
          ./generate_dockerfile.py
          if [ ! -f Dockerfile ]; then
            echo "❌ Failed to generate Dockerfile."
            exit 1
          fi

      - name: Print Dockerfile Contents
        run: |
          echo "📝 Dockerfile contents:"
          if [ -f Dockerfile ]; then
            cat Dockerfile
          else
            echo "❌ Dockerfile not found. Ensure it exists in the repository root if not generated."
            [ "${{ github.event.inputs.dockerfile }}" = "true" ] && exit 1 || echo "ℹ️ Assuming custom Dockerfile is provided."
          fi

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          if [[ -z "${{ env.APP_NAME }}" ]]; then
            echo "❌ ERROR: APP_NAME is empty. Exiting."
            exit 1
          fi
          docker build -t ${{ env.APP_NAME }}:$GITHUB_SHA .
          if [ $? -ne 0 ]; then
            echo "❌ Docker build failed."
            exit 1
          fi

      - name: Login to JFrog Artifactory
        env:
          JFROG_URL: ${{ secrets.JFROG_URL }}
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
        run: |
          echo "$JFROG_API_KEY" | docker login "$JFROG_URL" -u "$JFROG_USER" --password-stdin

      - name: Tag and Push Image to JFrog Artifactory
        env:
          JFROG_URL: ${{ secrets.JFROG_URL }}
        run: |
          docker tag ${{ env.APP_NAME }}:$GITHUB_SHA $JFROG_URL/docker-internal/${{ env.APP_NAME }}:$GITHUB_SHA
          docker push $JFROG_URL/docker-internal/${{ env.APP_NAME }}:$GITHUB_SHA

  manage-manifests:
    name: Manage Kubernetes Manifests
    needs: [ extract-metadata, build-and-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables from Job Outputs
        run: |
          echo "APP_NAME=${{ needs.extract-metadata.outputs.app_name }}" >> "$GITHUB_ENV"
          echo "NAMESPACE=${{ needs.extract-metadata.outputs.namespace }}" >> "$GITHUB_ENV"

      - name: Debug Extracted Variables
        run: |
          echo "✅ Extracted APP_NAME=${{ env.APP_NAME }}"
          echo "✅ Extracted NAMESPACE=${{ env.NAMESPACE }}"
        
      - name: Checkout Kustomize Repository
        uses: actions/checkout@v3
        with:
          repository: bgcodehub/kustomize-application
          path: kustomize-base

      - name: Install Dependencies
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
          sudo apt-get install -y jq
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          curl -LO https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar xf kubeconform-linux-amd64.tar.gz
          sudo mv kubeconform /usr/local/bin/

      - name: Validate Application Customization
        run: |
          if [[ "${{ github.event.inputs.application }}" != "go-api" && "${{ github.event.inputs.application }}" != "java-api" && "${{ github.event.inputs.modifications }}" != "{}" ]]; then
            echo "❌ Error: Runtime customization is only allowed for go-api and java-api"
            exit 1
          fi

      - name: Apply Runtime Modifications
        if: ${{ github.event.inputs.application == 'go-api' || github.event.inputs.application == 'java-api' }}
        run: |
          FILE=""
      
          if [[ "${{ github.event.inputs.application }}" == "go-api" ]]; then
            FILE="kustomize-base/go-api/overlays/patches/deploy.yaml"
          elif [[ "${{ github.event.inputs.application }}" == "java-api" ]]; then
            FILE="kustomize-base/java-api/overlays/patches/deploy.yaml"
          fi
      
          echo "🔹 Applying runtime modifications to $FILE"
          
          echo '${{ github.event.inputs.modifications }}' | jq -r 'to_entries | .[] | "\(.key) = \(.value)"' | while read -r line; do
            KEY=$(echo "$line" | cut -d'=' -f1 | xargs)
            VALUE=$(echo "$line" | cut -d'=' -f2 | xargs)
            echo "  - $KEY: $VALUE"
      
            if [[ "$KEY" == "timeout_seconds" || "$KEY" == "initial_delay_seconds" || "$KEY" == "revision_history_limit" || "$KEY" == "termination_grace_period_seconds" || "$KEY" == "max_replicas" ]]; then
              VALUE=$(echo "$VALUE" | jq 'tonumber')
            fi
      
            case "$KEY" in
              cpu_limit)
                yq -i '.spec.template.spec.containers[0].resources.limits.cpu = "'"$VALUE"'"' $FILE ;;
              memory_limit)
                yq -i '.spec.template.spec.containers[0].resources.limits.memory = "'"$VALUE"'"' $FILE ;;
              cpu_request)
                yq -i '.spec.template.spec.containers[0].resources.requests.cpu = "'"$VALUE"'"' $FILE ;;
              memory_request)
                yq -i '.spec.template.spec.containers[0].resources.requests.memory = "'"$VALUE"'"' $FILE ;;
              timeout_seconds)
                yq -i '.spec.template.spec.containers[0].livenessProbe.timeoutSeconds = '$VALUE'' $FILE ;;
              initial_delay_seconds)
                yq -i '.spec.template.spec.containers[0].livenessProbe.initialDelaySeconds = '$VALUE'' $FILE ;;
              revision_history_limit)
                yq -i '.spec.revisionHistoryLimit = '$VALUE'' $FILE ;;
              termination_grace_period_seconds)
                yq -i '.spec.template.spec.terminationGracePeriodSeconds = '$VALUE'' $FILE ;;
              max_replicas)
                yq -i '.spec.maxReplicas = '$VALUE'' "kustomize-base/java-api/overlays/patches/hpa.yaml" ;;
              *)
                echo "❌ Error: Invalid key '$KEY'. Skipping."
                continue ;;
            esac
          done
      
          echo "✅ Updates completed successfully!"
        
      - name: Generate Kubernetes ConfigMap with AWS Region and Environment
        run: |
          CONFIG_DIR="kustomize-base/${{ github.event.inputs.application }}/overlays/config"
          mkdir -p "$CONFIG_DIR"

          cat <<EOF > "$CONFIG_DIR/aws-configmap.yaml"
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: aws-config
          data:
            AWS_REGION: "${{ github.event.inputs.aws_region }}"
            ENV_NAME: "${{ github.event.inputs.env_name }}"
          EOF

          echo "✅ AWS ConfigMap generated at $CONFIG_DIR/aws-configmap.yaml"

      - name: Update Kustomization to Include ConfigMap
        run: |
          KUSTOMIZATION_FILE="kustomize-base/${{ github.event.inputs.application }}/overlays/kustomization.yaml"

          if ! grep -q "configMapGenerator" "$KUSTOMIZATION_FILE"; then
            echo -e "\nconfigMapGenerator:" >> "$KUSTOMIZATION_FILE"
          fi

          if ! grep -q "name: aws-config" "$KUSTOMIZATION_FILE"; then
            echo "  - name: aws-config" >> "$KUSTOMIZATION_FILE"
            echo "    literals:" >> "$KUSTOMIZATION_FILE"
            echo "      - AWS_REGION=${{ github.event.inputs.aws_region }}" >> "$KUSTOMIZATION_FILE"
            echo "      - ENV_NAME=${{ github.event.inputs.env_name }}" >> "$KUSTOMIZATION_FILE"
            echo "    options:" >> "$KUSTOMIZATION_FILE"
            echo "      disableNameSuffixHash: true" >> "$KUSTOMIZATION_FILE"
          fi

          echo "✅ Kustomization updated to include AWS ConfigMap without suffix."

      - name: Update Deployment to Reference ConfigMap
        run: |
          DEPLOYMENT_FILE="kustomize-base/${{ github.event.inputs.application }}/overlays/patches/deploy.yaml"
  
          yq -i '.spec.template.spec.containers[0].env += [{"name": "AWS_REGION", "valueFrom": {"configMapKeyRef": {"name": "aws-config", "key": "AWS_REGION"}}}]' $DEPLOYMENT_FILE
          yq -i '.spec.template.spec.containers[0].env += [{"name": "ENV_NAME", "valueFrom": {"configMapKeyRef": {"name": "aws-config", "key": "ENV_NAME"}}}]' $DEPLOYMENT_FILE
  
          echo "✅ Deployment updated to reference ConfigMap values."

      - name: Update Image in Kustomize Manifest
        env:
          JFROG_URL: ${{ secrets.JFROG_URL }}
        run: |
          IMAGE_URL="$JFROG_URL/docker-internal/$APP_NAME:$GITHUB_SHA"
          FILE="kustomize-base/${{ github.event.inputs.application }}/overlays/patches/deploy.yaml"

          echo "🔹 Updating image in $FILE to $IMAGE_URL"
          yq -i '.spec.template.spec.containers[0].image = "'"$IMAGE_URL"'"' $FILE
          echo "✅ Image updated successfully!"

      - name: Update Namespace in Base Kustomization
        run: |
          echo "🔹 Updating namespace in base/kustomization.yaml to: $NAMESPACE"
          yq -i '.namespace = strenv(NAMESPACE)' kustomize-base/base/kustomization.yaml
          echo "✅ Namespace updated successfully in base/kustomization.yaml"

      - name: Apply Kustomize Overlays and Output New Configuration
        env:
          NAMESPACE: ${{ env.NAMESPACE }}
        run: |
          APP_DIR="${{ github.event.inputs.application }}"
          mkdir -p "$APP_DIR"
          kustomize build "kustomize-base/${{ github.event.inputs.application }}/overlays/" > "$APP_DIR/deployment.yaml"
          echo "📝 New Updated Configuration:"
          cat "$APP_DIR/deployment.yaml"

      - name: Validate Kubernetes Manifests with Kubeconform
        run: |
          kubeconform -strict -summary -ignore-missing-schemas -schema-location default "${{ github.event.inputs.application }}/deployment.yaml"

      - name: Configure Git for Unsigned Commits
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global commit.gpgsign false
          git config --global gpg.program ""

      - name: Push Manifests to Atlas Repository
        env:
          GITHUB_TOKEN: ${{ secrets.ATLAS_GITHUB_PAT }}
        run: |
          set -e

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          REPO_URL=${{ github.event.inputs.atlas_repository }}
          AUTH_REPO_URL="https://x-access-token:${GITHUB_TOKEN}@${REPO_URL#https://}"
          TARGET_BRANCH="${{ github.event.inputs.env_name }}"

          echo "📥 Cloning Atlas repository branch: $TARGET_BRANCH..."
          git clone --branch "$TARGET_BRANCH" "$AUTH_REPO_URL" atlas
          
          if [[ "${{ github.event.inputs.aws_region }}" == "us-east-1" ]]; then
            TARGET_DIR="use1-01"
          elif [[ "${{ github.event.inputs.aws_region }}" == "us-west-2" ]]; then
            TARGET_DIR="usw2-01"
          else
            echo "❌ Error: Invalid AWS Region selected."
            exit 1
          fi

          FINAL_PATH="atlas/$TARGET_DIR/${{ github.event.inputs.application }}"
          echo "📂 Ensuring the directory structure exists: $FINAL_PATH"
          mkdir -p "$FINAL_PATH"

          echo "📤 Copying deployment files to $FINAL_PATH..."
          cp -r "${{ github.event.inputs.application }}"/* "$FINAL_PATH/"

          cd atlas

          echo "🧐 Checking for changes..."
          git status
          git diff || echo "ℹ️ No changes detected by git diff"

          git add -A
          git ls-files --others --exclude-standard

          if git diff --cached --quiet; then
            echo "✅ No changes detected. Skipping commit."
            exit 0
          fi

          echo "✅ Changes detected. Committing..."
          git commit -m "feat(deploy): update ${{ github.event.inputs.application }} manifests for ${{ github.event.inputs.env_name }} in ${{ github.event.inputs.aws_region }} - $GITHUB_SHA"

          echo "🚀 Pushing changes to branch: $TARGET_BRANCH..."
          git push origin "$TARGET_BRANCH"

  # trigger-argocd:
  #   name: Trigger ArgoCD Deployment
  #   needs: manage-manifests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Sync ArgoCD
  #       env:
  #         ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
  #         ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
  #       run: |
  #         curl -k -X POST "$ARGOCD_SERVER/api/v1/applications/my-app/sync" \
  #         -H "Authorization: Bearer $ARGOCD_TOKEN"

  # post-deployment:
  #   name: Post-Deployment Verification
  #   needs: trigger-argocd
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Notify Developers
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #       run: |
  #         curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment succeeded for $GITHUB_SHA"}' $SLACK_WEBHOOK